# _Classes with generics_

Ya hemos visto los gen√©ricos pero vamos a jugar un poquito m√°s aplic√°ndolos a
clases. Empezaremos creando un nuevo paquete llamado `generic_classes`.

Recordemos que los gen√©ricos permiten que una clase, funci√≥n o m√©todo trabaje
con diferentes tipos de datos, sin tener que conocer de antemano qu√© tipo de
datos ser√°n, permiten escribir c√≥digo m√°s flexible y reutilizable.

## Parecido a la vida real

Algo que van a hacer todo el tiempo cuando construyan sus aplicaciones, es pedir
informaci√≥n fuera de la aplicaci√≥n. Si bien ya veremos en detalle c√≥mo sucede
este proceso ahora me interesa que sepan que se resume de la siguiente manera:

1. Hacemos un pedido desde nuestra aplicaci√≥n a un servidor (_server_), una computadora que
   contiene informaci√≥n.
2. Seg√∫n lo que suceda, podemos tener a muy grandes rasgos, dos tipos de
   resultados: _success_ (√©xito) o _error_ (ü§∑üèª‚Äç‚ôÇÔ∏è).
3. Presentamos ese resultado al usuario.

__Es muy importante que el usuario en todo momento sepa qu√© est√° sucediendo en
nuestra aplicaci√≥n por lo que no solamente tenemos que mostrar los casos de
√©xitos (_happy path_ com√∫nmente llamado en ingl√©s) sino tambi√©n los casos de
fallo__ para que el usuario sepa qu√© hacer en ese momento.

Lo que quiero que creemos en este ejemplo es una clase que represente dicho
resultado.

## Simulando un _request_

__Vamos a empezar a simular c√≥mo ser√≠a un llamado a un servidor o tambi√©n
llamado un _request_ (pedido).__ No vamos a complicarnos con m√©todos as√≠ncronos
o m√©todos que demoran un tiempo y vamos a tener que esperar. Por ahora
simplemente vamos a crear un m√©todo llamado `processRequest` que nos retorne una
`String` si se trata de un error simulado o un tipo random seg√∫n nosotros le digamos.

Para ello, vamos a los tests de nuestro nuevo paquete y all√≠ crear un grupo de
la siguiente manera `group('Given a call to processRequest', () {});`.

All√≠, vamos a situar todos los requerimientos de nuestro m√©todo. Empecemos!

Dijimos que ese m√©todo ten√≠a que retornar un error o un √©xito. Estar√≠a bueno que
podamos decidir nosotros al momento de llamarlo si queremos que retorne un tipo
o el otro o lo que es lo mismo que decir, si queremos que produzca un fallo.
Podr√≠amos hacerlo as√≠:

```dart
import 'package:test/test.dart';

void main() {
  group('Given a call to processRequest', () {
    test(
        'When I call it with returnError = true, Then the result should be a String',
        () {});
  });
}
```

Ya tenemos el caso de uso o _use case_. Vamos a implementarlo y cuando digo
vamos, es üíÄ, vayan a implementarlo:

```dart
import 'package:test/test.dart';

void main() {
  group('Given a call to processRequest', () {
    test(
        'When I call it with returnError = true, Then the result should be a String with value Error',
        () {
      final result = processRequest(returnError: true);
      expect(result, isA<String>());
      expect(result, 'Error');
    });
  });
}
```

Varias cosas podemos ver en este ejemplo. En primer lugar, la funci√≥n
`processRequest` recibe un par√°metro `bool` para saber si tiene que arrojar un
error o algo m√°s. Por otro lado, ese resultado puede o bien ser un error o
bien algo m√°s si la operaci√≥n fue exitosa, por ahora en ambos casos, se tratar√°
de un `String`. Finalmente, si va a ser un error, dicha `String` ser√° `'Error'`.

__Ahora ya con nuestro caso de uso implementado, estamos obligados a dejar de
hacerlo fallar, implementando nuestro m√©todo.__ Vamos?

En el `generic_classes_base.dart` dentro de `lib/src`,üíÄ vayan a crear el m√©todo
prestando atenci√≥n en lo que hablamos. No hace falta que implementen el caso de
√©xito sino solamente el de error, aprendiendo as√≠ a no hacer _over-engineer_
que se refiere a la pr√°ctica de dise√±ar, construir o implementar algo de una
manera m√°s complicada o sofisticada de lo necesario (puede ser un problema ya
que puede aumentar el costo y la complejidad sin agregar valor real o mejorar la
calidad).

Esto es lo que hice:

```dart
processRequest({required bool returnError}) {
  if (returnError) {
    return 'Error';
  }
}
```

Muy simple verdad?. Si lo importamos en nuestro test, deber√≠a dar todo correctamente! Me alegro as√≠ haya sido! Hagan lo mismo con el otro caso de uso.

```dart
    test(
        'When I call it with returnError = false, Then the result should be a String with value Success',
        () {
      final result = processRequest(returnError: false);
      expect(result, isA<String>());
      expect(result, 'Success');
    });
```

Si lo corren ahora, van a poder observar c√≥mo falla ya que el `return` ahora es
`null`. Vayan a corregir la implementaci√≥n hasta que el test de correctamente:

```dart
processRequest({required bool returnError}) {
  if (returnError) {
    return 'Error';
  }
  return 'Success';
}
```

Ahora vamos a empezar a ajustarnos al requerimiento inicial: esta clase deber√≠a
poder retornar un tipo _random_ o aleatorio si se trata de un caso de √©xito y un
tipo espec√≠fico de fallo si se trata de un error. Podr√≠amos suponer una implementaci√≥n como la siguiente:

```dart
// Importamos la librer√≠a 'dart:math' para poder usar la clase 'Random'
import 'dart:math';

processRequest({required bool returnError}) {
  // Creamos una lista con varios tipos de datos
  var randomResult = [1, true, 'Hello', 3.14, 'World', false, 2];
  if (returnError) {
    // Si 'returnError' es true, devolvemos un error del tipo 'Failure' que aun
    // no hemos definido
    return Failure('This is an error');
  }

  // La clase Random nos permite generar n√∫meros aleatorios en un rango
  // determinado. En este caso, generamos un n√∫mero aleatorio entre 0 y 6.
  // El m√©todo 'nextInt' devuelve un n√∫mero entero aleatorio entre 0 y el
  // n√∫mero que le pasemos como par√°metro.
  // Dichos n√∫meros se corresponden con los √≠ndices de la lista 'randomResult'
  return randomResult[Random().nextInt(7)];
}
```

Vamos a ir por partes. Primero qu√© les parece si creamos una clase `Failure` que
reciba un `String` a modo de mensaje para comunicar qu√© sucedi√≥? Con ella van a
ver que nuestro m√©todo deja de fallar.

```dart
class Failure {
  final String message;
  Failure(this.message);
}
```

Ahora bien: c√≥mo podemos realizar un test de un m√©todo como el anterior? Hasta
ahora solo retornaba un `String` que podr√≠amos haberlo especificado antes de la
siguiente manera:

```dart
String processRequest({required bool returnError}) {
  if (returnError) {
    return 'Error';
  }
  return 'Success';
}
```

Sin embargo, ya no es el caso con el nuevo m√©todo ya que podr√≠a retornar un
`String` o bien cualquier otro tipo. Podr√≠amos utilizar un retorno de tipo
`dynamic` pero no sabr√≠amos si dicho retorno es un error o es un caso de √©xito.
C√≥mo podemos hacer?

## Creando la clase _Result_

Podr√≠amos crear una clase llamada `Result` que pueda alojar ambos tipos de
resultados, en `value` y `error`, siendo este √∫ltimo del tipo `Failure`. Vamos
de a poco si? üíÄ Arranquen desde la creaci√≥n de un test de dicha clase en donde
la inicialicemos con un caso de √©xito y corroboremos que el resultado no sea un
`Failure`:

```dart
  group('Given a Result class', () {
    late Result result;
    test(
        'When created with a success use case, Then Result.value should not be a Failure',
        () {
      result = Result('Success');
      expect(result.value, isNot(isA<Failure>()));
    });
  });
```

Ya con esto, tenemos material suficiente para crear nuestro primer `Result`.
üíÄ H√°ganlo ustedes primero si? Vale mencionar que tienen que correr solamente
los tests de este grupo ya que el grupo que creamos antes destinado a testear
`processRequest` va a comenzar a fallar.

```dart
class Result {
  final dynamic value;
  final Failure? error;

  Result({this.value, this.error});
}
```

Qu√© les parece si testeamos el caso inverso?

```dart
      test(
         'When created with an error use case, Then Result.error should be a Failure',
         () {
      result = Result(error: Failure('Error'));
      expect(result.error, isA<Failure>());
      });
```

## _Generics in methods_

Vamos aunque no me convence tener dentro del `Result` representado como caso de
√©xito un `value` del tipo `dynamic`. Por qu√©? En la mayor√≠a de los casos cuando
hagan una petici√≥n (otra forma de llamar al _request_), van a saber qu√© tipo
tiene que retornar; no es que van a tener un tipo aleatorio. De esta forma, si
nosotros quisi√©ramos poder trabajar con el resultado, no podr√≠amos hacerlo.
D√©jenme ejemplificarlo:

```dart
    test(
        'When created with a success use case, Then Result.value should be an int',
        () {
      result = Result(value: 'Success');
      expect(result.value, isA<int>());
    });
```

Eso ser√≠a un test de una parte de nuestra aplicaci√≥n que har√≠a un _request_ en
el que sabemos que si todo sali√≥ de la manera esperada, deber√≠amos tener un
`int` como resultado; sino, un `String`. Sin embargo, nuestra clase `Result` nos
permite instanciarla con un valor del tipo `String` por lo que obviamente dicho
test va a fallar.

__C√≥mo podr√≠amos restringir el tipo de valor que queremos en nuestra clase?__
Podr√≠amos utilizar _generics_. C√≥mo lo hacemos? Ya lo mencionamos cuando los
utiliz√°bamos en funciones pero suceder√° lo mismo en las clases: entre `< >`
ponemos una letra may√∫scula para representar lo que esperamos que reciba,
utilizando alguna de las convenciones siguientes:

- `E` para elemento.
- `K` y `V` para key y value respectivamente.
- `R` para un tipo de retorno.
- `T`, `S` y `U` para tipos gen√©ricos.
- Si ninguno de los tipos anteriores sirvi√≥ a nuestros fines, cualquier letra
  may√∫scula puede servir.

Si creamos nuestra clase recibiendo un gen√©rico:

```dart
class Result<T> {
  final T? value;
  final Failure? error;

  Result({this.value, this.error});
}
```

Podremos luego entonces, hacer esto:

```dart
    test(
        'When created with a success use case, Then Result.value should be an int',
        () {
      result = Result<int>(value: 1);
      expect(result.value, isA<int>());
    });
```

C√≥mo nos damos cuenta de que esto nos sirve? Prueben hacer lo siguiente:

```dart
    test(
        'When created with a success use case, Then Result.value should be an int',
        () {
      result = Result<int>(value: 'Success');
      expect(result.value, isA<int>());
    });
```

No nos deja ni siquiera compilar ya que nos dice que el valor del tipo `String`
no puede asignarse a uno del tipo `int` y esto es hermosamente poderoso ya que
nos permite tener una clase que podremos reutilizar tantas veces como queramos:

```dart
    test(
        'When created with a success use case of value type int, Then Result.value should be an int',
        () {
      result = Result<int>(value: 1);
      expect(result.value, isA<int>());
    });

    test(
        'When created with a success use case  of value type String, Then Result.value should be a String',
        () {
      result = Result<String>(value: 'Success');
      expect(result.value, isA<String>());
    });
    test(
        'When created with a success use case  of value type bool, Then Result.value should be a bool',
        () {
      result = Result<bool>(value: false);
      expect(result.value, isA<bool>());
    });
```

Incluso, podr√≠amos pasarle otro par√°metro e incluso limitar nuestro `Result` de la siguiente manera:

```dart
class Result<T, F extends Exception> {
  final T? value;
  final F? error;

  Result({this.value, this.error});
}
```

Esto nos permitir√≠a obligar a que el error pueda lanzar una `Exception`:

```dart
class AppException implements Exception {
  final String message;

  AppException(this.message);

  @override
  String toString() => message;
}
```

```dart
    test(
        'When created with an error use case, Then Result.error should be an AppException',
        () {
      result = Result<int, AppException>(error: AppException('Error'));
      expect(result.error, isA<AppException>());
      expect(() => throw(result.error!), throwsException); //üëÅÔ∏è
    });
```

Y una __importante aclaraci√≥n:  en Dart, las excepciones no son valores, por lo que no pueden ser pasadas directamente como argumentos de una funci√≥n. En lugar de eso, se necesita envolver la excepci√≥n en una funci√≥n an√≥nima que la lance para que la funci√≥n `expect` pueda capturar la excepci√≥n.__

En este caso espec√≠fico, `expect(() => throw(result.error!), throwsException);` est√° diciendo que espera que la funci√≥n an√≥nima que se pasa como argumento `(() => throw(result.error!))` lance una excepci√≥n (`throwsException`). Es decir, el test espera que cuando se llame a la funci√≥n an√≥nima, esta lance la excepci√≥n `result.error!` y que el test capture dicha excepci√≥n.

## üí™ Poniendo los tests al d√≠a

__Requirement__: actualicen todos los tests para adaptarse a estos
√∫ltimos modelos.

```dart
// Importamos la librer√≠a 'dart:math' para poder usar la clase 'Random'

import 'dart:math';

Result<int, AppException> processRequest({required bool returnError}) {
  // Creamos una lista con un tipo de dato gen√©rico int
  var randomResult = [1, 0, 1, 1, 0, 1, 0];
  if (returnError) {
    return Result(error: AppException('This is an error'));
  }

  return Result(value: randomResult[Random().nextInt(6)]);
}

class AppException implements Exception {
  final String message;

  AppException(this.message);

  @override
  String toString() => message;
}

class Result<T, F extends Exception> {
  final T? value;
  final F? error;

  Result({this.value, this.error});
}
```

__Soluci√≥n__:

```dart
import 'package:generic_classes/generic_classes.dart';
import 'package:test/test.dart';

void main() {
  group('Given a Result class', () {
    late Result result;
    test(
        'When created with a success use case, Then Result.value should not be an AppException',
        () {
      result = Result(value: 'Success');
      expect(result.value, isNot(isA<AppException>()));
    });

    test(
        'When created with a success use case of value type int, Then Result.value should be an int',
        () {
      result = Result<int, AppException>(value: 1);
      expect(result.value, isA<int>());
    });

    test(
        'When created with a success use case  of value type String, Then Result.value should be a String',
        () {
      result = Result<String, AppException>(value: 'Success');
      expect(result.value, isA<String>());
    });
    test(
        'When created with a success use case  of value type bool, Then Result.value should be a bool',
        () {
      result = Result<bool, AppException>(value: false);
      expect(result.value, isA<bool>());
    });

    test(
        'When created with an error use case, Then Result.error should be an AppException',
        () {
      result = Result<int, AppException>(error: AppException('Error'));
      expect(result.error, isA<AppException>());
      expect(() => throw (result.error!), throwsException);
    });
  });

  group(
    'Given a call to processRequest',
    () {
      test(
          'When I call it with returnError = true, Then the result should be a Result with value of AppException and message This is an error',
          () {
        final result = processRequest(returnError: true);
        expect(result.error, isA<AppException>());
        expect(result.error?.message, 'This is an error');
      });

      test(
          'When I call it with returnError = false, Then the result should be a Result with value of type int',
          () {
        final result = processRequest(returnError: false);
        expect(result.value, isA<int>());
      });
    },
  );
}
```
