# `async` and `await`

Recuerdan que en la clase previa dijimos que la forma de manejar futuros no era
la mejor? Permítanme mostrarles el por qué con un ejemplo.

Imaginen que cuando el proceso de pedir una mesa termina, queremos hacer otros
dos pedidos de mesa para unos amigos. Así es cómo se vería:

```dart
void main() {
  print('🚀 The process has started!');
  askForTable(5).then((value) {
    if (value == true) {
      print('You have a table! 🥳');
    } else {
      print('You don\'t have a table! 😋');
    }
    // El método catchError se ejecuta cuando se produce un error
  }).catchError((error) {
    print('Error: $error');
  }).whenComplete(() => askForTable(3).then((value) {
        if (value == true) {
          print('You have a table! 🥳');
        } else {
          print('You don\'t have a table! 😋');
        }
      }).catchError((error) {
        print('Error: $error');
      }).whenComplete(() => askForTable(4).then((value) {
            if (value == true) {
              print('You have a table! 🥳');
            } else {
              print('You don\'t have a table! 😋');
            }
          }).catchError((error) {
            print('Error: $error');
          }))).whenComplete(() => print('Now has ended! 😭'));
}
```

Una verdadera locura verdad? Vamos a ir de a poco viendo una forma mucho más
práctica de trabajar con operaciones asíncronas. Vamos a partir del primer
ejemplo:

```dart
void main() {
  print('🚀 The process has started!');
  askForTable(5).then((value) {
    if (value == true) {
      print('You have a table! 🥳');
    } else {
      print('You don\'t have a table! 😋');
    }
    // El método catchError se ejecuta cuando se produce un error
  }).catchError((error) {
    print('Error: $error');
  }).whenComplete(() => print('The process has finished! 🤓'));
}
```

Ahora, en lugar de escribir todo eso, vamos a hacer lo siguiente:

```dart
void main() {
  print('🚀 The process has started!');
  final firstOrder = await askForTable(5); // 👁️
  print(firstOrder);
}
```

Lo que queremos es trabajar con el resultado de nuestra función, aunque si lo
corren, van a obtener `Instance of 'Future<bool>'`, ya que no estamos esperando
a dicho futuro. Y cómo lo hacemos? Simplemente agregando la _keyword_ `await`
(esperar por) delante del método:

```dart
void main() {
  print('🚀 The process has started!');
  final firstOrder = await askForTable(5);
  print(firstOrder);
}
```

Sin embargo, al hacerlo Dart les indica: _'The await expression can only be used
in an async function.'_ Nos dice que podemos utilizar `await` solamente en
funciones asíncronas y para ello, basta con marcar la función con `async` de la
siguiente manera:

```dart
void main() async { // 👁️
  print('🚀 The process has started!');
  final firstOrder = await askForTable(5);
  print(firstOrder);
}
```

Esto convierte a la función en una asíncrona, haciéndola posible de esperar por
aquellos métodos que son asíncronos. Si ahora imprimen, van a poder ver el
resultado luego de los segundos de _delay_ que implementamos:

```shell
🚀 The process has started!
false
Exited
```

Ya sabemos entonces cómo esperar por una función que toma tiempo pero qué sucede
si el futuro lanza una excepción?

```dart
Future<bool> askForTable(int diners) {
  return Future.delayed(Duration(seconds: 3), () {
    throw Exception('No tables available');
    if (diners > 4) {
      return false;
    } else {
      return true;
    }
  });
}
```

Tendríamos un error ya que no fue manejada:

```shell
🚀 The process has started!
Unhandled exception:
Exception: No tables available
#0      askForTable.<anonymous closure>
general.dart:18
#1      new Future.delayed.<anonymous closure> (dart:async/future.dart:424:39)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

Exited (255)
```

Cómo podemos hacerlo? Utilizando el ya conocido bloque `try {} catch (e) {}`:

```dart
void main() async {
  print('🚀 The process has started!');
  bool firstOrder;
  try {
    firstOrder = await askForTable(5);
    print(firstOrder);
  } catch (e) {
    print('Error: ${e}');
  }
}
```

Y ahora sí, veríamos lo siguiente:

```shell
🚀 The process has started!
false
Exited
```

Y si quisiéramos hacer más de un pedido, noten qué simple se vuelve de leer:

```dart
void main() async {
  print('🚀 The process has started!');
  bool firstOrder;
  bool secondOrder;
  bool thirdOrder;
  try {
    firstOrder = await askForTable(5);
    print(firstOrder);
    secondOrder = await askForTable(4);
    print(secondOrder);
    thirdOrder = await askForTable(3);
    print(thirdOrder);
  } catch (e) {
    print('Error: ${e}');
  } finally {
    print('🚀 The process has ended!');
  }
}
```

```shell
🚀 The process has started!
false
true
true
🚀 The process has ended!
Exited
```

Y podríamos volverlo más _user friendly_ tal como el primer ejemplo:

```dart
void main() async {
  print('🚀 The process has started!');
  bool firstOrder;
  bool secondOrder;
  bool thirdOrder;
  try {
    firstOrder = await askForTable(5);
    printResult(firstOrder);
    secondOrder = await askForTable(4);
    printResult(secondOrder);
    thirdOrder = await askForTable(3);
    printResult(thirdOrder);
  } catch (e) {
    print('Error: ${e}');
  } finally {
    print(' The process has ended! 🥳');
  }
}

void printResult(bool value) {
  if (value == true) {
    print('You have a table! 🥳');
  } else {
    print('You don\'t have a table! 😋');
  }
}
```

```shell
🚀 The process has started!
You don't have a table! 😋
You have a table! 🥳
You have a table! 🥳
 The process has ended! 🥳
Exited
```

## 💪 Cronómetro

__Requirement__: crear una función llamada `printSeconds` que reciba un `int value` y
un `bool returnError` para generar un error adrede que se pueda testear. Dicha función tiene que
imprimir los segundos hasta llegar al `value` incluyéndolo. El mismo, no puede superar el
número 60 y esto debe controlarse mediante _assertions_. Al finalizar, tienen
que imprimir 'Done ⚡️' y retornar un valor de `true` si no sucedió ningún
problema y lanzar una excepción si sucedió. Deben demostrarlo haciendo uso de la
función en caso de éxito por un lado y error por el otro, manejando la excepción
en el último caso y escribiendo los tests respectivos.

__💀 Solution__:

### Tests

#### Utilizando `expectLater`

```dart
import 'package:test/test.dart';

void main() {
  group('Given a printSeconds with N as value', () {
    test('When value is greater than 60, Then throws AssertionError', () {
      expectLater(printSeconds(value: 61, returnError: false),
          throwsA(isA<AssertionError>()));
    });

    test('When ends correctly, Then returns true after N seconds', () {
      expectLater(
          printSeconds(value: 2, returnError: false), completion(isTrue));
    });

    test('When something went wrong, Then throws an exception after N seconds',
        () {
      expectLater(printSeconds(value: 2, returnError: true), throwsException);
    });
  });
}
```

#### Utilizando `async await`

```dart
void main() {
  group('Given a printSeconds with N as value', () {
    test('When value is greater than 60, Then throws AssertionError', () {
      expect(() => printSeconds(value: 61, returnError: false),
          throwsA(isA<AssertionError>()));
    });

    test('When returnError is true, Then throws Exception', () {
      expect(() => printSeconds(value: 30, returnError: true),
          throwsA(isA<Exception>()));
    });

    test('When all parameters are valid, Then returns true', () async {
      final result = await printSeconds(value: 5, returnError: false);
      expect(result, isTrue);
    });
  });
}
```

### Función

```dart
Future<bool> printSeconds({
  required int value,
  required bool returnError,
}) async {
  assert(value <= 60, 'Value must be less than 60 seconds');
  if (returnError) throw Exception('Something went wrong!');
  for (var i = 0; i < value; i++) {
    await Future.delayed(Duration(seconds: 1));
    print('⏲ Seconds: ${i + 1}');
  }
  print('Done ⚡️');
  return true;
}
```

### Implementación

```dart
void main() async {
  try {
    await printSeconds(value: 10, returnError: false);
    await printSeconds(value: 10, returnError: true);
  } catch (e) {
    print(e);
  }
}
```
